### ISSUE TITLE
Math Alfabet

### ISSUE THREAD

**Issue by demozylak** [demozylak/BackyardCrypto#6]
Trzeba sprawdzać czy klucz jest prawidłowy : czy wszystkie literki są unikalne 
w sensie zeby nie bylo klucza 
"aaaaaaaaaaaaa..." xD

**Comment by aerfio** [comment]
u wot m8?
Czyli mam sprawdzic czy w tym co zwroci key->getPassword() nie ma powtarzajacych sie znakow? Przeciez to powinna sprawdzac jakas funkcja/konsruktor przy tworzeniu klucza (bo klucz z powtarzajacymi sie znakami to nie klucz)

**Comment by demozylak** [comment]
tak , ale klasa klucz (a tym bardziej input ) nie ma pojęcia o tym co przenosi xd

**Comment by aerfio** [comment]
no to k, ja to sprawdze u sb
